package org.ac.cst8277.ismail.hamdi.ums.controller;

import org.ac.cst8277.ismail.hamdi.ums.model.Roles;
import org.ac.cst8277.ismail.hamdi.ums.repository.RolesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/roles")
public class RolesController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private RolesRepository rolesRepository;

@PostMapping(path="/add") // Map ONLY POST Requests
public @ResponseBody String addNewRole (@RequestParam String role
 , @RequestParam String desc) {
// @ResponseBody means the returned String is the response, not a view name
// @RequestParam means it is a parameter from the GET or POST request

Roles n = new Roles(role,desc);
rolesRepository.save(n);
return "Saved";
}

@GetMapping(path="/all")
public @ResponseBody Iterable<Roles> getAllRoles() {
// This returns a JSON or XML with the users
return rolesRepository.findAll();
}

}
