package org.ac.cst8277.ismail.hamdi.ums.controller;

import java.util.Optional;

import org.ac.cst8277.ismail.hamdi.ums.model.User;
import org.ac.cst8277.ismail.hamdi.ums.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import jakarta.transaction.Transactional;

@RestController
@RequestMapping("/api/users")
public class UserController {
	
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private UserRepository userRepository;


@GetMapping(path="/all")
public @ResponseBody Iterable<User> getAllUsers() {
// This returns a JSON or XML with the users
return userRepository.findAll();
}

@Transactional
@DeleteMapping("/delete/{id}")
public @ResponseBody String deleteUser (@PathVariable("id") Long id) {
	Optional<User> existingUser = userRepository.findById(id);
  if (existingUser.isPresent()) {
	  userRepository.deleteById(id);
	  return "User deleted";
  } else {
	  return "User not found or does not exist";
  }
}
	

}
