spring.application.name=ums
server.port=8090
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://localhost:3306/ums-db?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=Abu23rahma!

spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=create
spring.jpa.hibernate.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always

spring.security.oauth2.client.registration.github.clientId=Ov23liGwBxHaFm3R7rIo
spring.security.oauth2.client.registration.github.clientSecret=cb7beefb40fa0a79390e0fc810a44e139693b818