package com.example.twitter_clone.controller;


import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.example.twitter_clone.model.Message;
import com.example.twitter_clone.repository.MessageRepository;

@RestController
@RequestMapping("/api/messages")
public class MessageController {
	
	
	@Autowired // This means to get the bean called MessageRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private MessageRepository messageRepository;

@PostMapping(path="/add") 
public @ResponseBody String addNewMessage (@RequestParam String content
 , @RequestParam Long userId) {

Message n = new Message(content,userId);
messageRepository.save(n);
return "Saved";
}

@GetMapping(path="/all")
public @ResponseBody Iterable<Message> getAllMessages() {
return messageRepository.findAll();
}

@GetMapping("/producer/{id}")
public @ResponseBody List<Message> findByProducer(@PathVariable("id") Long id) {
	Message n = new Message("This producer does not have any content",id);
	if(messageRepository.findByUserId(id).size()<1) {
		List<Message> list = new ArrayList<Message>();
		list.add(n);
		return list;
	}
	return messageRepository.findByUserId(id);
}

@GetMapping("/subscriber/{id}")
public List<Message> getMessagesBySubscriberId(@PathVariable("id") Long id) {
	Message n = new Message("This user does not subscribe to any content",id);
	if(messageRepository.findMessagesBySubscriberId(id).size()<1) {
		List<Message> list = new ArrayList<Message>();
		list.add(n);
		return list;
	} else {
    return messageRepository.findMessagesBySubscriberId(id);
	}
}

}
